name: GraphGT
tagline: "GraphGT: Machine Learning Datasets for Deep Graph Generation and Transformation"
analytics: UA-
logo:
  image: static/images/logo.png
  width: 40px
  height: auto
# uncomment the following line to show the site title next to the logo image
# site_title: DLG4NLP
page_title:
  prefix: 'GraphGT'
  separator: ': '
background_image: static/images/main.jpeg
organization: GraphGT Team


# Configuration for auth
#Test user
#user: miniconf@miniconf.com
#pass: mIniconf1_

use_auth0:
auth0_client_id : JIdr6wi0z27LyLgwkJF0fpk700aj7MNH
auth0_domain : miniconf.auth0.com

calendar:
  colors: #  Colors for the different event hashtags:
    ---: '#bed972'
    qa: '#4FCAEB'
    talk: '#ccc'
  sunday_saturday: false  #  Include Sunday and Saturday
